---
- name: Run OpenSCAP Evaluation and optionally Remediation
  hosts: all
  become: yes
  vars:
    run_remediation: false  # Overridable: -e run_remediation=true
    upload_url: "http://10.20.11.117:2112/upload"

  tasks:

    - name: Run remediation script (optional)
      shell: bash /opt/openscap/run_remediation.sh
      when: run_remediation
      tags: [remediate]

    - name: Run evaluation script
      shell: bash /opt/openscap/run_evaluation.sh
      register: eval_output
      ignore_errors: true
      changed_when: false

    - name: Extract ARF path from evaluation output
      set_fact:
        arf_result_path: "{{ eval_output.stdout | regex_search('RESULTS_ARF_PATH=(.*)', '\\1') }}"
      when: eval_output.stdout is defined

    - name: Upload ARF result via curl
      shell: |
        curl -X POST {{ upload_url }} \
          -F "target={{ ansible_hostname }}" \
          -F "report=@{{ arf_result_path }}"
      when: arf_result_path is defined
